### ISSUE TITLE
Index.npz请教

### ISSUE THREAD

**Issue by Andy-HuY** [XDZhelheim/STAEformer#11]
作者您好，请问如果我想试试其他的数据集，这里如果需要读取Index.npz我该如何生成这样的文件呢？谢谢

**Comment by XDZhelheim** [comment]
你好！
可以参考：
1. https://github.com/XDZhelheim/Torch-MTS/blob/main/scripts/generate_training_data.py
2. https://github.com/zezhishao/BasicTS/blob/master/scripts/data_preparation/METR-LA/generate_training_data.py

**Comment by Andy-HuY** [comment]
好的，谢谢



---原始邮件---
发件人: "Zheng ***@***.***&gt;
发送时间: 2024年7月30日(周二) 上午10:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XDZhelheim/STAEformer] Index.npz请教 (Issue #11)




 
你好！
 可以参考：
  
https://github.com/XDZhelheim/Torch-MTS/blob/main/scripts/generate_training_data.py
 
https://github.com/zezhishao/BasicTS/blob/master/scripts/data_preparation/METR-LA/generate_training_data.py
