### ISSUE TITLE
非常好的代码

### ISSUE THREAD

**Issue by Suasy** [XDZhelheim/STAEformer#4]
跑完了实验，感觉这个训练和模型的框架非常值得学习，写得非常的清晰明了👍

**Comment by ownnaruto** [comment]
同意，非常的简洁清晰，而且复现结果基本一致

**Comment by XDZhelheim** [comment]
感谢朋友们的认可哈哈，感兴趣的话可以关注我另一个公开项目，大号的训练框架。任何相关问题都欢迎交流！

**Comment by Suasy** [comment]
请问作者我可以在你的代码基础上进行修改和做我的工作吗，届时会添加引用和以及仓库说明，不知道可不可以🙏

**Comment by Suasy** [comment]
> 感谢朋友们的认可哈哈，感兴趣的话可以关注我另一个公开项目，大号的训练框架。任何相关问题都欢迎交流！

请问作者我可以在你的代码基础上进行修改和做我的工作吗，届时会添加引用和以及仓库说明，不知道可不可以🙏

**Comment by XDZhelheim** [comment]
当然可以。本来就是开源的，声明代码引用和论文引用就行。

**Comment by Suasy** [comment]
好的谢谢！
