### ISSUE TITLE
与STID的区别

### ISSUE THREAD

**Issue by 376498485** [XDZhelheim/STAEformer#7]
您好，我看了论文和代码，发现与STID的区别就是加了两个attention，想问一下还有其他区别吗？

**Comment by HankLiu10** [comment]
看得不太对，建议再看看

**Comment by XDZhelheim** [comment]
首先我们不是在STID上加了俩transformer，建议对比代码最直观。
其次，**标题: Spatio-Temporal Adaptive Embedding** 才是本文的核心贡献点。
![image](https://github.com/XDZhelheim/STAEformer/assets/57553691/5dd508d1-a5d4-4145-b526-39ed7fb54053)

**Comment by 376498485** [comment]
你所提出的adaptive embedding和STID中的spatial embedding区别在哪？代码里都是随机初始化的可学习参数，论文里可视化了adaptive embedding，和STID论文中的spatial embedding可视化结果是一样的，都是出现了结点之间的聚合现象。

**Comment by XDZhelheim** [comment]
你好，我们的ST adaptive embedding是一个全新的时空混合的做法。相比于spatial embedding，具有捕捉时间关系的能力。您还可以参考fig 3中的实验，以及fig 4(b)，这些是spatial embedding不具备的。

**Comment by 376498485** [comment]
行吧行吧，就是初始化的时候不太一样，spatial embedding初始化为N*D的shape，你们的初始化为L*N*D的shape，就是多了一个维度，所以解释为有了捕捉时间关系的能力，不知道我理解的是否准确。

**Comment by XDZhelheim** [comment]
可以从shape上做最直观的理解。另外因果关系是，我们先有让其有捕捉时间能力的想法，再有的时间维度，而不是刻意解释成为了捕捉时间的。

**Comment by 376498485** [comment]
好的谢谢，看了你们的工作我深受启发，感谢。

**Comment by XDZhelheim** [comment]
嗯嗯，这个话题确实是一个关键点，也感谢您的提问。如有其它问题也欢迎随时交流。
