### ISSUE TITLE
attn_layers_t(x, dim=1)与attn_layers_s(x, dim=2)

### ISSUE THREAD

**Issue by turmony** [XDZhelheim/STAEformer#9]
非常感谢您的工作，我有一点不明白，时间注意力层传入的dim=1和空间注意力层传入的dim=2的作用是什么？
`        for attn in self.attn_layers_t:
            x = attn(x, dim=1)
        for attn in self.attn_layers_s:
            x = attn(x, dim=2)`

**Comment by XDZhelheim** [comment]
你好，dim指attention作用的维度。
传入数据维度为 (B, T, N, H)，dim=1指在T维上做（时间），dim=2指在N维上做（空间）。

请参考定义：
https://github.com/XDZhelheim/STAEformer/blob/2dfb9e35c2f04bbb7136657100ea3d8afa5fc4e5/model/STAEformer.py#L6-L13
https://github.com/XDZhelheim/STAEformer/blob/2dfb9e35c2f04bbb7136657100ea3d8afa5fc4e5/model/STAEformer.py#L94-L98

**Comment by LayCYL** [comment]
您好，想问一下，在数据嵌入层的第三块的时空自适应嵌入，在代码data_prepare中没看到有体现
